# Generated by Django 4.2.2 on 2023-08-12 19:14

from django.db import migrations, models
import e_commerce_store.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=20, validators=[e_commerce_store.accounts.validators.letters_only_validator]),
        ),
    ]
