# Generated by Django 4.2.2 on 2023-08-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_created=True, default='2023-08-04'),
            preserve_default=False,
        ),
    ]
