# Generated by Django 4.2.2 on 2023-08-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
