# Generated by Django 4.2.2 on 2023-07-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitstoreuser',
            name='profile_picture',
            field=models.URLField(default='photo'),
            preserve_default=False,
        ),
    ]
