# Generated by Django 4.2.2 on 2023-07-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fruitstoreuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitstoreuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
