# Generated by Django 4.2.2 on 2023-08-09 20:44

import django.core.validators
from django.db import migrations, models
import e_commerce_store.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_fruitstoreuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitstoreuser',
            name='first_name',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(30), e_commerce_store.accounts.validators.letters_only_validator]),
        ),
        migrations.AlterField(
            model_name='fruitstoreuser',
            name='last_name',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(30), e_commerce_store.accounts.validators.letters_only_validator]),
        ),
    ]
