# Generated by Django 4.2.2 on 2023-08-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_fruitstoreuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitstoreuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
