# Generated by Django 4.2.2 on 2023-08-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_fruitstoreuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitstoreuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
